# Terminal (WezTerm)
bindsym $mod+Return exec wezterm start --cwd .


# Browser (Zen Flatpak)
bindsym $mod+b exec /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh app.zen_browser.zen
#
# File manager
bindsym $mod+f exec xdg-open .


# Kdenlive AppImage
bindsym $mod+k exec /home/yeasin/apps/kdenlive-26.04.0-x86_64.AppImage

# Screenshot select area
bindsym $mod+Shift+s exec gnome-screenshot -a

# Emoji picker
bindsym Control+period exec /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=emoji-mart io.github.vemonet.EmojiMart


# Move the current window to the "other" monitor
bindsym $mod+Shift+greater move container to output right
bindsym $mod+Shift+less move container to output left

# Move your actual focus (the cursor) to the other monitor
bindsym $mod+greater focus output right
bindsym $mod+less focus output left
