[colors]
foreground = "#F9EEE0"
background = "#2F2920"
cursor_bg = "#B3A28B"
cursor_fg = "#2F2920"
cursor_border = "#B3A28B"
selection_fg = "#F9EEE0"
selection_bg = "#A69B8D"

ansi = [
  "#4D4742",
  "#ED9529",
  "#A36B1D",
  "#C76912",
  "#4D9220",
  "#8F5E19",
  "#526616",
  "#EEDECA",
]

brights = [
  "#A69B8D",
  "#ED9529",
  "#A36B1D",
  "#C76912",
  "#4D9220",
  "#8F5E19",
  "#526616",
  "#EEDECA",
]
