theme[main_bg]="#2F2920"
theme[main_fg]="#F9EEE0"

theme[title]="#4D9220"
theme[hi_fg]="#526616"

theme[selected_bg]="#4D9220"
theme[selected_fg]="#2F2920"

theme[inactive_fg]="#A69B8D"

theme[cpu_box]="#ED9529"
theme[mem_box]="#A36B1D"
theme[net_box]="#4D9220"
theme[proc_box]="#8F5E19"

theme[div_line]="#A69B8D"
theme[temp_start]="#A36B1D"
theme[temp_mid]="#C76912"
theme[temp_end]="#ED9529"

theme[graph_text]="#F9EEE0"
theme[meter_bg]="#4D4742"
