### --- Monitor Configuration ---


# swaymsg 'output HDMI-A-1 mode 3840x2160 scale 2 pos 0 0; output DP-3 mode 1280x1024 transform 90 pos 1920 0'


output HDMI-A-1 {
    mode 1920x1080
    pos 0 0
}

output DP-3 {
    mode 1280x1024
    transform 90
    pos 1920 0
}

# Main Monitor - Shifted down by 200px to align bottoms
# Forces a 3840x2160 logical canvas for OBS
# output HDMI-A-1 {
#     mode 1920x1080
#     scale 0.5
#     pos 0 0
# }

# Shifted to 3840 so the mouse crosses over seamlessly
# output DP-3 {
#     mode 1280x1024
#     transform 90
#     scale 1
#     pos 3840 0
# }


### --- UI / Mouse ---
# seat * cursor_size 24
# exec_always gsettings set org.cinnamon.desktop.interface cursor-size 24

### --- Workspace Assignments ---
workspace 1 output HDMI-A-1
workspace 2 output HDMI-A-1
workspace 3 output HDMI-A-1
workspace 4 output DP-3
workspace 5 output DP-3
workspace 6 output DP-3
