### --- Monitor Configuration ---
output HDMI-A-1 {
    mode 1920x1080
    pos 0 0
}

output DP-3 {
    mode 1280x1024
    transform 90
    pos 1920 0
}

### --- UI / Mouse ---
# seat * cursor_size 24
# exec_always gsettings set org.cinnamon.desktop.interface cursor-size 24

### --- Workspace Assignments ---
workspace 1 output HDMI-A-1
workspace 2 output HDMI-A-1
workspace 3 output HDMI-A-1
workspace 4 output DP-3
workspace 5 output DP-3
workspace 6 output DP-3
